stages:
  - docker
  - deploy
services:
  - docker:dind
docker-job:
  stage: docker
  image: docker:dind
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t registry.gitlab.com/omegaprime2008/fiat-backend .
    - docker push registry.gitlab.com/omegaprime2008/fiat-backend:latest

image:
  name: registry.gitlab.com/omegaprime2008/fiat-backend:latest
  entrypoint: [""]

.job_deploy: &job_deploy
  stage: deploy

deploy_dev:
  <<: *job_deploy
  when: manual
  script:
    - pip install awscli
    - pip install lightsailctl
    - aws lightsail push-container-image fiat-backend --image registry.gitlab.com/omegaprime2008/fiat-backend:latest
  environment:
    name: development


